require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/doctors", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Doctor. As you add validations to Doctor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "Dr. Hynes",
      address: "Stanford University",
      image_url: "doctor1_image.png",
      fees: 0.56789e5,
      busy_slots: ['07:30 1'],
      start_time: '06:30',
      end_time: '10:30'
    }
  }

  let(:invalid_attributes) {
    {
      address: "Celebrium, Human Brain",
      image_url: "doctor2_image.png",
      start_time: '06:30',
      end_time: '10:30'
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Doctor.create! valid_attributes
      get doctors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      doctor = Doctor.create! valid_attributes
      get doctor_url(doctor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_doctor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      doctor = Doctor.create! valid_attributes
      get edit_doctor_url(doctor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Doctor" do
        expect {
          post doctors_url, params: { doctor: valid_attributes }
        }.to change(Doctor, :count).by(1)
      end

      it "redirects to the created doctor" do
        post doctors_url, params: { doctor: valid_attributes }
        expect(response).to redirect_to(doctor_url(Doctor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Doctor" do
        expect {
          post doctors_url, params: { doctor: invalid_attributes }
        }.to change(Doctor, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post doctors_url, params: { doctor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end
  describe "DELETE /destroy" do
    it "destroys the requested doctor" do
      doctor = Doctor.create! valid_attributes
      expect {
        delete doctor_url(doctor)
      }.to change(Doctor, :count).by(-1)
    end

    it "redirects to the doctors list" do
      doctor = Doctor.create! valid_attributes
      delete doctor_url(doctor)
      expect(response).to redirect_to(doctors_url)
    end
  end
end
