default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DEV_DB"] %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_TEST_DB"] %>

production:
  <<: *default
  username: <%= ENV['POSTGRES_PROD_USER'] %>
  password: <%= ENV['POSTGRES_PROD_PASSWORD'] %>
  host: <%= ENV['POSTGRES_PROD_HOST'] %>
  database: <%= ENV["POSTGRES_PROD_DB"] %>
